#!/usr/bin/bash

: '
manual preparations: getmail/<server>.<kind>_<email>
e.g.
pass insert getmail/imap_smtp.993_puntaier.roland@gmail.com
pass insert getmail/mail.pops_testpops@fellowsandcarr.ca
pass insert getmail/mail.imaps_testimaps@fellowsandcarr.ca
refresh clamav:
sudo freshclam
run for each:
export MWNOTMUCHNEW=1
export MWNOTMUCHNEW=0

Needs on arch:
pacman -S neomutt isync getmail6 msmtp notmuch-runtime pass urlscan

All tests (from root directory):

export mwaddr="puntaier.roland@gmail.com"
make test
'

echo
echo Unit Test:
echo
bats --tap test_mw.bats

bash test_getmail.sh

echo
echo "Integration tests need working email $mwaddr"

if [ -z "$MAILDIR" ] || [ -z "$mwaddr" ]; then
    echo "First do:"
    [ -z "$MAILDIR" ] && echo "export MAILDIR=..."
    [ -z "$mwaddr" ] && echo "export mwaddr=your.email@gmail.com"
    exit
fi

export PREFIX=$PWD/mwtesttmp
export PATH=$PATH:$PREFIX/bin

cd .. && make install && OK="OK"

if [ "$OK" = "OK" ]; then

    echo "Warning: Out with CTRL-C if your mail (config) files are important here."
    read

    export mwmaildir=$MAILDIR
    export mwname='r n'
    export mwlogin=$mwaddr
    export mwpass="${mwpass:-mailwizard-$mwaddr}"
    mwaccmaildir="$mwmaildir/$mwaddr"

    rm -rf $mwaccmaildir

    [ -f "${PASSWORD_STORE_DIR:-~/.password-store}/$mwpass.gpg" ] || pass insert $mwpass

    echo "= Test 1 ="
    echo $PATH
    mwtype=online mw add
    echo "=> In another prompt, start mutt and verify that mails are shown"
    echo "=> Then answer with N"
    mw purge
    rm -rf $mwaccmaildir

    echo "= Test 2 ="
    mwtype=offline mw add
    mw

    echo "=> In another prompt, add 'mailwizard/test/mwtesttmp/bin' to PATH"
    echo "=> Start mutt and verify that mails are shown"
    echo "=> Press i1, wait, press i2. Verify that mutt is fast again after i2."
    echo "=> Press gm and gM, to start mw sync."
    echo "=> Answer with Y and check that isync/mbsyncrc, msmtp/config and mutt/accounts are gone."
    mw purge

fi

cd $CD

rm -rf $PREFIX

